language: python
dist: xenial
sudo: required
python:
- '3.7'
services:
- docker
notifications:
  email:
    on_success: never
    on_failure: change
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - bash
    - coreutils
    - awscli
cache:
  directories:
  - "/home/travis/.nvm"
  - "/home/travis/.cache/pip"
env:
  global:
  - BOTO_CONFIG: "/dev/null"
  - LOG_LEVEL: ERROR
  - secure: SFiDMqcO61t8pzxWp55WMEhC0keqpxfKcLjN5MZiFTtTB1tZCwnZDBUx8rbnIJfU8MAnUPB0pK/tNQghkJwpdMg05pefD4ZJuprXuRYeH0E6z98eAyOFktZExXQqtxW7ESrvb91Eso/T7tsQb0b4jbsGyhVBHAhhc/kBqyqVfVQmN6tT38NfyLN8kSibybsxp5xoA2NyuPP/c89VC+e5lnrJHECQHf62HdA9vTcySrnX81gkWVTriyJc+vkiVFV0FWwSyl3DfbLkN5qiw85mBs3rop1bViJkJHK3UlXiW5MuDgI1iGTlA8uQMJrjlF3dZ6HKTOYWPgcoKK48losvOTtv7rorhKg8rCHZdmTsaqOzYae8XcrLgBeWphUzVUP32NW4SrdY9JB59L9ht2PoJMoFxMipXkeOqk+GEnCdyiKicewYcT1UsJfpvz4Yw3OReDzKQ//UHNPjFOQ46x0QQKb017H41cM15QerEAiI9PJ/AfZkbxrbrmLvxAUnoahSHQCW6RB7WR04hL4hZ95sY5QhV8cqSkU9iP+SExNbRC8cPcNLU7KYEE4q6hzXwY4ZPjetJSzF1Gp8HfL9C1zh/rpWX0Nxzl54J5aJpdzTXASQdonT9RDIR3gf/bQIou6EKtQLTybgj+9CTr/MxfjjK99pA4MHc0y389+pyEM0Y5M=
  - secure: jfGlcaBs3vdQ+nycb/JX7JP2nf9vBa7LtA0+Pp6lDm/6V6LrVmF955ldHyaZjMchxQJCinVBOzU5++XWAg0wG/jponQ5ZBpuGpqsefA5y7PDoYk7XZib7VE+PTm5PlPI14JcB5FRgCeDfJQR+XBCgnvCnWM8k2cF5HJEODQovw/r3xkGC6j3IQU1JJkQCT6rTuvZ6GGbxU/bFCrjK1PjQqw3d1qmYfvbLU3dCwYGpL/a3eqwheINIPQq7mtorCHZ7BkN/1B907sIvEH72LUwZgJTckBcbCbxgjKMtGYbYWEoH6DteUTzZo4zok5nTArsMOqYHYRoC9rezMJz8C1f5tB/ktclCgAoiM1QGMr5/6PHrOU61iQms+8SCOZZ6iRql7TGL/6P+zFXMFql6MOQ5JmxwKYXTo36l+QaGeqU4yxzCKoDbpMuUTymP215XaYWC1njQHcOgWdNgzbXOvjWvpgEPa2ivp2/64zOnCsZhHpkwdiNPye4VrefOoOqrSUTNi7fsFmEPFNbrOp/v5QGrpapfPb+w7hIeabrVa5bQyCH/hOQThcpDqaZa9MnD2ZcI53A8tznAScG5k8Ei1CKRjo3ZtSW25dgPr5eDRlWbHEhCWwOvymnw4mFqJVE58m17UOBqgm3MJzWOhJg5PFg/0zqJzgjBEDB0WeLTHpVq/Q=
before_install:
- sudo rm -f /etc/boto.cfg
- pip install -r automation_requirements.txt
script:
- tox
- bash bin/aws-credentials.sh
- bash bin/deploy.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
dd:
  secure: qD9bvYWn7qqMYsvEvH7+4+R7gsxTQUSwuqzA//0Cibx+PE4VuW5yXIObdOGf60x33MVy2bEsika8sZJ8wDt1Eldx3c1qtm7c3AwRADQ7rWl3766A7T01mJ9HEIH5ST6Ch31cm6BApLjmnQMHMmYv0Zevf6vgBQIj9HK4YZhUMopiUvQ+0FiWKATPbxa/YodyNllhHaf51rQs6tXYMwAdZnFbCWYVdF2DbXp7D+5iqhZohKNPcgtLg8QXLvLZMgXw20+54fqo0vOaEKkTMfri6iuMuhW3/X1mokPBt4+4FX5+AYH74xMCM3G1durc3/Em1hcZaa0Nm6gH2KhILyx5VUSei7S0ufsCRcO0gTxQi64+jgNgT/J7spmOm/w5qNbEos7KptGd86jNV2ISegTYD+OLGwCM/ZUKieMmgx8hVRlAyR1AOe/yag5RbA/xGwYaVqCvlT4nMt/dbxUpWJgU98ufjewrNRi8VZK03QzD2apeYaHby+NL2lqdVRA3lNrc8JkJq1rE7cRZ1YcW0OZg255XHCk49qr2s7lfqEFweCN5PBWerP9F78DWBpDHV+47vUSSgUWilWb2HPCaWixb9mHoXqWymCOpp1h8WelfuHItwAQNQTyoqRtsQl3Eop8Cga127A9ujgSPF8SqtU1i6IjIbYN145EaLBK6rPhFuqg=
