# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

language: python
dist: xenial
sudo: required
python:
 - "3.7"
services:
 - docker
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test']
    packages: ['bash', 'coreutils', 'awscli','curl','unzip','zip','openjdk-8-jdk','curl','graphviz']
cache:
  directories:
    - /home/travis/.nvm
    - /home/travis/.cache/pip
env:
  global:
    - BOTO_CONFIG: "/dev/null"
    - LOG_LEVEL: ERROR
    - AWS_XRAY_SDK_ENABLED: false
    - DEPLOYED_ENV: travis

before_install:
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - sudo apt-get update && sudo apt-get install -y bazel
  - sudo apt-get install -y --only-upgrade bazel
  - sudo rm -f /etc/boto.cfg
  - sudo apt-get install -y awscli
  - ./bin/aws-credentials.sh

jobs:
  include:
    - stage: Unit Tests
      script:
        - bazel test //...
